language: php
before_script: 
  - composer self-update
  - composer install
php:
  - 5.5
  - 5.6
script:
  - phpunit --bootstrap vendor/autoload.php tests/
notifications:
  - email: true
matrix:
  fast_finish: true
